name: workflowNewman
on: [push, pull_request]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install --global newman newman-reporter-htmlextra

      - name: Run Postman Collection
        run: newman run https://www.getpostman.com/collections/ba47e81be11dcbfcaae0 -r htmlextra

      - name: Publier le rapport HTML
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report-${{ github.run_id }}
          path: newman/*.html
