name: workflowNewman
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Check out Git repositor
      uses: actions/checkout@v1
    - name: Install newman
      run: npm install -g newman
    - name: Run the API and Postman's tests
      run: echo hello
